### ISSUE TITLE
Cannot get pretty URL

### ISSUE THREAD

**Issue by xperseguers** [xperseguers/t3ext-file_list#25]
As we started to discuss with @mediaessenz, there seems to be problems getting TYPO3 v9 generate pretty URL for this extension.

No rewriting configuration generates URL

```
http://v9.typo3dev.loc/en/files?tx_filelist_filelist%5Baction%5D=list&tx_filelist_filelist%5Bcontroller%5D=File&tx_filelist_filelist%5Bpath%5D=%2Fuser_upload%2Ftest%2F&cHash=564878e90f3e80900bc9cbe9d7169282
```

With this configuration:

```
  FileListPlugin:
    type: Extbase
    limitToPages: [5]
    extension: FileList
    plugin: Filelist
    routes:
      -
        routePath: '/directory{path}'
        _controller: 'File::list'
        _arguments:
          path: path
    requirements:
      path: .+
```

this generates URL

```
http://v9.typo3dev.loc/en/files/directory/user_upload/test/?cHash=b9101a4d5384f3f30f6099e576a1edba
```

* This is prettier but there's still a `cHash` parameter
* It fails anyway with `Request parameters could not be validated (&cHash comparison failed)`

**Comment by xperseguers** [comment]
When generating the links, the `cHash` is calculated four times, once with:

<img width="621" alt="Screenshot 2020-07-06 at 10 42 51" src="https://user-images.githubusercontent.com/646805/86574060-887a0b80-bf75-11ea-82b4-1d85aaf1cc9d.png">

giving `cHash=564878e90f3e80900bc9cbe9d7169282`.

Another time with:

<img width="619" alt="Screenshot 2020-07-06 at 10 44 31" src="https://user-images.githubusercontent.com/646805/86574160-b2333280-bf75-11ea-9ada-e4c19f4a4583.png">

giving `cHash=b9101a4d5384f3f30f6099e576a1edba`.

and once again the same two first generations, in same order.

The pretty URL is using `cHash=b9101a4d5384f3f30f6099e576a1edba`.

Now, when clicking the pretty link, it fails because the `cHash` is calculated with:

<img width="621" alt="Screenshot 2020-07-06 at 10 49 35" src="https://user-images.githubusercontent.com/646805/86574656-7482d980-bf76-11ea-899f-90222b8f2253.png">

(mind the missing trailing slash)

**Comment by mediaessenz** [comment]
Maybe the first calculation it not used in the end, because of a skipDefaultArguments = 1 definition in the global extbase typoscript feature key of your test environment?

But in the end it seems the cHash problem comes from the missing tailing slash.

As far as i remember, there where similar problems with normal urls, which could be solved with an additional routeEnhancer definition:
```yaml
  PageTypeSuffix:
    type: PageType
    default: '/'
    index: ''
    map:
      '/': 0
```
Unfortunately this is not usable in this case, i think.
